# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

language: python
python: 2.7

env:
    - OMV_ENGINE=NEURON
    - OMV_ENGINE=Brian
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON

before_install:
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-sympy

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
