# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: trusty
sudo: false  

addons:
  apt:
    packages:
    - python-matplotlib 
    - python-sympy
    - python-numpy 
    - python-scipy 

language: python
python: 2.7

virtualenv:
system_site_packages: true

env:
    - OMV_ENGINE=NEURON
    - OMV_ENGINE=Brian
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON

install: 
    - pip install scipy # Why is this needed? Doesn't seem to get installed correctly on trusty with addons above...
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
